###
GET http://localhost:8080/

### 
GET http://localhost:8080/65ce7072ab54a010db35ea9f HTTP/1.1

####
Post http://localhost:8080/ HTTP/1.1
Content-Type: application/json

 {
    "name": "Charmander",
    "pokedexId": "007",
    "type1": "Fire",
    "type2": "None",
    "favoriteColor": "?"
  }

####
Put http://localhost:8080/65ce7072ab54a010db35ea9f  HTTP/1.1
Content-Type: application/json

    {
    "name": "Charmander",
    "pokedexId": "007",
    "type1": "Fire",
    "type2": "None",
    "favoriteColor": "Red"
    }

####
Delete http://localhost:8080/65ce7ca54aad4177d9cd3602  HTTP/1.1

# Render links vv

####
Get https://pokemon-ktdm.onrender.com HTTP/1.1

###
Get https://pokemon-ktdm.onrender.com/ HTTP/1.1

####
Post https://pokemon-ktdm.onrender.com HTTP/1.1
Content-Type: application/json

 {
    "name": "Charmander",
    "pokedexId": "007",
    "type1": "Fire",
    "type2": "None",
    "favoriteColor": "?"
  }

####
Put https://pokemon-ktdm.onrender.com/
Content-Type: application/json

    { "favoriteColor": "White" }

####
Delete https://pokemon-ktdm.onrender.com HTTP/1.1